language: rust
sudo: false

matrix:
  include:
    - env: CC=gcc-4.8 CXX=g++-4.8
      rust: stable
      os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - libcurl4-openssl-dev
            - libelf-dev
            - libdw-dev
            - g++-4.8

    - env: CC=gcc-4.8 CXX=g++-4.8
      rust: beta
      os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - libcurl4-openssl-dev
            - libelf-dev
            - libdw-dev
            - g++-4.8

    - env: CC=gcc-4.8 CXX=g++-4.8
      rust: nightly
      os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - libcurl4-openssl-dev
            - libelf-dev
            - libdw-dev
            - g++-4.8

    - env: CC=clang CXX=clang++
      rust: stable
      os: osx

    - env: CC=clang CXX=clang++
      rust: beta
      os: osx

    - env: CC=clang CXX=clang++
      rust: nightly
      os: osx

script:
  - cargo test --all
  - rustup component add rustfmt
  - cargo fmt --all -- --check
  - cargo build --release

notifications:
  email: false
